name: impact_waves
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  lottie: ^3.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets\logo.png
   - assets\ngo.png
   - assets\don_img.jpg
   - assets\digg_img.jpg
   - assets\class_img.jpg
   
   - assets\child_img.jpg
   - assets\done_img.jpg
   - assets\water_pulse.json
   - assets\water_drop_1.json
   - assets\water_drop_2.json
   - assets\particle.json
   - assets\wave.json
